repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: node
        entry: eslint
        args:
          - --fix
        files: \.(js)$
        additional_dependencies:
          - babel-eslint@^10.0.3
          - eslint@^6.8.0

          - eslint-config-defaults@^9.0.0
          - eslint-config-standard@^14.1.1
          - eslint-config-standard-react@^9.2.0

          - eslint-import-resolver-webpack@^0.12.1

          - eslint-plugin-import@^2.20.2
          - eslint-plugin-react@^7.18.3
          - eslint-plugin-standard@^4.0.1
          - eslint-plugin-node@^11.1.0
          - eslint-plugin-promise@^4.2.1
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --indent=2
          - --autofix
          - --no-sort-keys
      - id: trailing-whitespace
